<?php

/**
 * OpenBuilt Placeholder Resolver
 *
 * Resolves template placeholder tokens (e.g. {{appId}}) inside the embedded
 * nextcloud-app-template snapshot during an export. Pure, deterministic,
 * idempotent: re-resolving an already-resolved string is a no-op.
 *
 * @category Service
 * @package  OCA\OpenBuilt\Service
 *
 * @author    Conduction Development Team <dev@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git-id>
 *
 * @link https://conduction.nl
 *
 * @SPDX-License-Identifier: EUPL-1.2
 * @SPDX-FileCopyrightText:  2026 Conduction B.V. <info@conduction.nl>
 */

declare(strict_types=1);

namespace OCA\OpenBuilt\Service;

/**
 * Resolves placeholder tokens for the exporter.
 *
 * Token format: {{tokenName}} — replaced wholesale.
 * Literal renames: legacy template strings (`app-template`, `AppTemplate`)
 * are replaced with the exported app's slug / namespace so the unzipped tree
 * builds standalone with no further hand-edits.
 */
final class PlaceholderResolver
{
    /**
     * Returns the placeholder map for the exported app.
     *
     * @param array<string,string> $context Per-export values:
     *                                      appId, appNamespace, appName,
     *                                      appDescription, appVersion,
     *                                      authorName, authorEmail, license.
     *
     * @return array<string,string> Map of search → replace.
     */
    public function buildMap(array $context): array
    {
        $appId        = $this->slug(value: ($context['appId'] ?? 'my-app'));
        $appNamespace = $this->pascalCase(value: ($context['appNamespace'] ?? $appId));

        return [
            // Curly-brace placeholders for files that opt-in.
            '{{appId}}'          => $appId,
            '{{appNamespace}}'   => $appNamespace,
            '{{appName}}'        => (string) ($context['appName'] ?? $appNamespace),
            '{{appDescription}}' => (string) ($context['appDescription'] ?? 'A Nextcloud app generated by OpenBuilt.'),
            '{{appVersion}}'     => (string) ($context['appVersion'] ?? '0.1.0'),
            '{{authorName}}'     => (string) ($context['authorName'] ?? 'Conduction Development Team'),
            '{{authorEmail}}'    => (string) ($context['authorEmail'] ?? 'dev@conduction.nl'),
            '{{license}}'        => (string) ($context['license'] ?? 'EUPL-1.2'),
            // Literal renames so the unzipped tree builds standalone.
            'app-template'       => $appId,
            'AppTemplate'        => $appNamespace,
            'app_template'       => str_replace('-', '_', $appId),
            'App Template'       => (string) ($context['appName'] ?? $appNamespace),
        ];
    }//end buildMap()

    /**
     * Resolves placeholders in the given string.
     *
     * @param string               $content Source content.
     * @param array<string,string> $map     Placeholder map from buildMap().
     *
     * @return string Resolved content.
     */
    public function resolve(string $content, array $map): string
    {
        if ($content === '' || $map === []) {
            return $content;
        }

        return strtr($content, $map);
    }//end resolve()

    /**
     * Slug-cases an identifier (lowercase letters, digits, hyphens).
     *
     * @param string $value Source value.
     *
     * @return string Slug.
     */
    public function slug(string $value): string
    {
        $slug = strtolower(trim($value));
        $slug = preg_replace('/[^a-z0-9]+/', '-', $slug) ?? '';
        $slug = trim($slug, '-');
        if ($slug === '') {
            return 'my-app';
        }

        return $slug;
    }//end slug()

    /**
     * PascalCase'd identifier suitable for a PHP namespace.
     *
     * Splits on:
     *   - hyphens, underscores, whitespace, and any other non-alphanumeric;
     *   - camelCase boundaries (lowercase followed by uppercase), so
     *     `MyCoolApp` survives as `My`/`Cool`/`App` and is re-cased correctly.
     *
     * Each segment is then lowercased and ucfirst'd. This makes
     * pascalCase() idempotent: pascalCase(pascalCase($x)) === pascalCase($x).
     *
     * @param string $value Source value.
     *
     * @return string PascalCase'd identifier.
     */
    public function pascalCase(string $value): string
    {
        // Insert a separator at camelCase boundaries: lower→Upper and Upper→UpperLower.
        // Example: 'MyCoolApp' → 'My_Cool_App'; 'XMLParser' → 'XML_Parser'.
        $boundaryMarked = (string) preg_replace('/(?<=[a-z0-9])(?=[A-Z])/', '_', $value);
        $boundaryMarked = (string) preg_replace('/(?<=[A-Z])(?=[A-Z][a-z])/', '_', $boundaryMarked);

        $parts = preg_split('/[^A-Za-z0-9]+/', $boundaryMarked) ?: [];
        $out   = '';
        foreach ($parts as $part) {
            if ($part === '') {
                continue;
            }

            $out .= ucfirst(strtolower($part));
        }

        if ($out === '') {
            return 'MyApp';
        }

        return $out;
    }//end pascalCase()
}//end class
